# Dependencies
#markdown:         redcarpet
#pygments:         true

# Permalinks
permalink:        pretty

# setup
title:            Thanh Ngo
tagline:          ''
description:      ''
url: http://www.trungthanh.com

author:
  name:           'Thanh Ngo'
  url:            http://www.trungthanh.com
